RandomPlacer:
  limit:
    x: 500
    z: 500
    nx: -500
    nz: -500
  Teleported: You are now at {x}, {z}
  cooldown: 5
  #change to always teleport to a specific world
  world: all
  #Add in RandomPlacer.(world name).limit.x/z/nx/nz for world specific limits
Error:
  NumberConflict: The numbers set in the config do not work. Setting to 1000...
  NNumberNotSet: The negative numbers in the config are not set. Defaulting to -1000...
  NumberNotSet: The numbers in the config are not set. Defaulting to 1000...
  ConsoleSender: You must be a player to execute this command.
  Cooldown: You must wait for randomplacer to cooldown! ({cooldown} second{s} left)
