RandomPlacer:
  limit:
    x: 500
    z: 500
    nx: -500
    nz: -500
  world_the_end:
    limit:
      x: 300
      z: 300
      nx: -300
      nz: -300
  Teleported: You are now at {x}, {z}
  cooldown: 5
