name: RandomPlacer
version: 2.0
main: com.nasonfish.randomplacer.RandomPlacer

commands:
  tpr: 
    description: Teleports you to a random location
    permission: RandomPlacer.use
    alaises: tprandom 
    usage: /tpr
    
permissions: 
  RandomPlacer.use:
    default: true
    