name: RandomPlacer
version: 1.1.2
main: me.zippy120.RandomPlacer

commands:
  tpr: 
    description: Teleports you to a random location
    permission: RandomPlacer
    alaises: tprandom 
    usage: /tpr
    
permissions: 
  RandomPlacer:
    default: true
    